# Generated by Django 2.1.5 on 2019-01-23 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagSurivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('medication', models.IntegerField(default=0)),
                ('ammunition', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LastLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('infected', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lastlocation',
            name='survivor',
            field=models.OneToOneField(on_delete='CASCATE', related_name='last_location', to='core.Survivor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='survivor',
            field=models.ForeignKey(blank=True, on_delete='CASCATE', related_name='inventory', to='core.Survivor'),
        ),
        migrations.AddField(
            model_name='flagsurivor',
            name='author',
            field=models.ForeignKey(on_delete='CASCATE', related_name='flagging_counter', to='core.Survivor'),
        ),
        migrations.AddField(
            model_name='flagsurivor',
            name='target',
            field=models.ForeignKey(on_delete='CASCATE', related_name='flag_counter', to='core.Survivor'),
        ),
    ]
