# Generated by Django 2.1.5 on 2019-01-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivor',
            old_name='age',
            new_name='ageses',
        ),
    ]
