# Generated by Django 2.1.5 on 2019-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[(4, 'Water'), (3, 'Food'), (2, 'Medication'), (1, 'Ammunition')], default=0, max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='survivor',
            name='infected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='survivor',
            field=models.OneToOneField(on_delete='CASCATE', related_name='invetory', to='core.Survivor'),
        ),
    ]
