# Generated by Django 2.1.5 on 2019-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190113_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='survivor',
            field=models.ForeignKey(on_delete='CASCATE', related_name='inventory', to='core.Survivor'),
        ),
    ]
