# Generated by Django 2.1.5 on 2019-01-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190123_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivor',
            old_name='ageses',
            new_name='age',
        ),
    ]
