# Generated by Django 2.1.5 on 2019-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190113_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastlocation',
            name='survivor',
        ),
        migrations.AddField(
            model_name='survivor',
            name='last_location',
            field=models.OneToOneField(default=0, on_delete='CASCATE', related_name='survivor', to='core.LastLocation'),
            preserve_default=False,
        ),
    ]
