# Generated by Django 2.1.5 on 2019-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190123_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='survivor',
            field=models.OneToOneField(blank=True, on_delete='CASCATE', related_name='inventory', to='core.Survivor'),
        ),
    ]
