# Generated by Django 2.1.5 on 2019-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190113_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='last_location',
            field=models.OneToOneField(null=True, on_delete='CASCATE', related_name='survivor', to='core.LastLocation'),
        ),
    ]
