# Generated by Django 2.1.5 on 2019-01-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190123_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlagSurivor',
            new_name='FlagSurvivor',
        ),
        migrations.AlterField(
            model_name='lastlocation',
            name='survivor',
            field=models.OneToOneField(null=True, on_delete='CASCATE', related_name='last_location', to='core.Survivor'),
        ),
    ]
