# Generated by Django 2.1.5 on 2019-01-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190113_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='last_location',
        ),
    ]
