# Generated by Django 2.1.5 on 2019-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_survivor_last_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='last_location',
            field=models.OneToOneField(null=True, on_delete='CASCATE', related_name='survivor', to='core.LastLocation'),
        ),
    ]
