# Generated by Django 2.1.5 on 2019-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_survivor_last_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='last_location',
        ),
        migrations.AddField(
            model_name='lastlocation',
            name='survivor',
            field=models.OneToOneField(default=None, on_delete='CASCATE', to='core.Survivor'),
            preserve_default=False,
        ),
    ]
