# Generated by Django 2.1.5 on 2019-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190113_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastlocation',
            name='survivor',
            field=models.OneToOneField(default=None, null=True, on_delete='CASCATE', related_name='last_location', to='core.Survivor'),
        ),
    ]
