# Generated by Django 2.1.5 on 2019-01-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190117_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='flag_survivor',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='survivor',
            name='infected_counter',
            field=models.IntegerField(default=0),
        ),
    ]
