# Generated by Django 2.1.5 on 2019-01-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190117_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='survivor',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCATE', related_name='inventory', to='core.Survivor'),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='infected_counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
