# Generated by Django 2.1.5 on 2019-01-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190117_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='flag_survivor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
