# Generated by Django 2.1.5 on 2019-01-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190117_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='flag_survivor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
