# Generated by Django 2.1.5 on 2019-01-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190117_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='flag_survivor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
